DROP TABLE IF EXISTS jobs;

CREATE TABLE jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_path TEXT NOT NULL,
  job_type TEXT NOT NULL,
  email TEXT NOT NULL,
  status TEXT NOT NULL
);
